"""

Revision ID: a3afc053c284
Revises: e65d9d795f85
Create Date: 2022-11-06 15:02:23.745780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3afc053c284'
down_revision = 'e65d9d795f85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('characteristics', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'characteristics')
    # ### end Alembic commands ###
