"""commit

Revision ID: fa134896bfbc
Revises: f45aaa2081ec
Create Date: 2022-11-08 16:11:22.028138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa134896bfbc'
down_revision = 'f45aaa2081ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
